//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoletaDetalle
    {
        public int id { get; set; }
        public int idBoleta { get; set; }
        public int idAdmMateria { get; set; }
    
        public virtual AdmMateria AdmMateria { get; set; }
        public virtual Boleta Boleta { get; set; }
    }
}
