//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boleta()
        {
            this.BoletaDetalle = new HashSet<BoletaDetalle>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int estado { get; set; }
        public int idEstudiante { get; set; }
        public int idCarrera { get; set; }
        public string descripcion { get; set; }
        public string respuesta { get; set; }
        public string numReferencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoletaDetalle> BoletaDetalle { get; set; }
    }
}
