//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoAperturado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupoAperturado()
        {
            this.RegistroDeMateria = new HashSet<RegistroDeMateria>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> Folio { get; set; }
        public short CupoOfertado { get; set; }
        public short IdOferta { get; set; }
        public short IdMateriaContenido { get; set; }
        public short IdTurno { get; set; }
        public int IdUsuario { get; set; }
        public short IdSistemaEstudio { get; set; }
        public short IdEstadoGrupo { get; set; }
        public int IdDocente { get; set; }
        public short IdTipoEvaluacion { get; set; }
        public int IdTipoGrupoAperturado { get; set; }
        public decimal CostoMateria { get; set; }
        public short IdDescripcionGrupo { get; set; }
        public Nullable<long> IdGrupoAperturadoMaestro { get; set; }
    
        public virtual Turno Turno { get; set; }
        public virtual OfertaSistemaEstudio OfertaSistemaEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroDeMateria> RegistroDeMateria { get; set; }
    }
}
