//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyeccionEntities : DbContext
    {
        public ProyeccionEntities()
            : base("name=ProyeccionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmMateria> AdmMateria { get; set; }
        public virtual DbSet<AdmProyeccion> AdmProyeccion { get; set; }
        public virtual DbSet<Boleta> Boleta { get; set; }
        public virtual DbSet<BoletaDetalle> BoletaDetalle { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolPermisos> RolPermisos { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
