//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modulo()
        {
            this.AdmProyeccion = new HashSet<AdmProyeccion>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> semestre { get; set; }
        public Nullable<int> numModulo { get; set; }
        public Nullable<int> gestion { get; set; }
        public Nullable<int> idMes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmProyeccion> AdmProyeccion { get; set; }
    }
}
