//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaSistemaEstudio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfertaSistemaEstudio()
        {
            this.GrupoAperturado = new HashSet<GrupoAperturado>();
        }
    
        public short IdOferta { get; set; }
        public short IdSistemaEstudio { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.DateTime FechaLimitePago { get; set; }
        public System.DateTime FechaLimiteInscripcion { get; set; }
        public Nullable<System.DateTime> FechaExamenParcial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoAperturado> GrupoAperturado { get; set; }
        public virtual Oferta Oferta { get; set; }
    }
}
