//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oferta()
        {
            this.OfertaSistemaEstudio = new HashSet<OfertaSistemaEstudio>();
        }
    
        public short Id { get; set; }
        public short IdGestion { get; set; }
        public short NumeroPeriodo { get; set; }
        public short NroOfertaPeriodo { get; set; }
        public short IdGrupoAcademico { get; set; }
        public string Descripcion { get; set; }
        public short IdSistemaEnsenanza { get; set; }
        public short IdEstadoOferta { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<short> NroOrden { get; set; }
        public Nullable<short> IdSede { get; set; }
        public Nullable<int> IdMoodleCategoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfertaSistemaEstudio> OfertaSistemaEstudio { get; set; }
    }
}
