//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanEstudioMateria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanEstudioMateria()
        {
            this.Prerequisitos = new HashSet<Prerequisitos>();
            this.Prerequisitos1 = new HashSet<Prerequisitos>();
        }
    
        public int IdMateria { get; set; }
        public short IdPlanEstudio { get; set; }
        public Nullable<short> Periodo { get; set; }
        public Nullable<short> Creditos { get; set; }
        public Nullable<short> NumeroPeriodo { get; set; }
        public Nullable<short> HorasTeoricas { get; set; }
        public short HorasPracticas { get; set; }
        public Nullable<short> HorasAutonomas { get; set; }
        public Nullable<short> HorasTeoricasVirtuales { get; set; }
        public Nullable<short> HorasPracticasVirtuales { get; set; }
        public Nullable<int> TotalHrs { get; set; }
        public Nullable<short> IdEstadoMateria { get; set; }
        public int IdTipoMateria { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual PlanEstudio PlanEstudio { get; set; }
        public virtual TipoMateria TipoMateria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prerequisitos> Prerequisitos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prerequisitos> Prerequisitos1 { get; set; }
    }
}
