//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prerequisitos
    {
        public int IdMateria { get; set; }
        public short IdPlanEstudio { get; set; }
        public int IdMateriaPrerequisito { get; set; }
        public short IdPlanEstudioprequisito { get; set; }
        public string Descripcion { get; set; }
    
        public virtual PlanEstudioMateria PlanEstudioMateria { get; set; }
        public virtual PlanEstudioMateria PlanEstudioMateria1 { get; set; }
    }
}
