//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolPermisos
    {
        public int id { get; set; }
        public int idRol { get; set; }
        public int idPermisos { get; set; }
    
        public virtual Permisos Permisos { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
