//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTipoConvalidacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubTipoConvalidacion()
        {
            this.Traspaso = new HashSet<Traspaso>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<short> IdTipoConvalidacion { get; set; }
        public Nullable<short> TipoUniversidad { get; set; }
        public Nullable<short> IncluyeUProceso { get; set; }
        public Nullable<short> UniversidadVisible { get; set; }
        public Nullable<short> CarreraHabilitada { get; set; }
    
        public virtual TipoConvalidacion TipoConvalidacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traspaso> Traspaso { get; set; }
    }
}
