//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traspaso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Traspaso()
        {
            this.DetalleConvalidacion = new HashSet<DetalleConvalidacion>();
            this.DetalleHomologacion = new HashSet<DetalleHomologacion>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaInformeTecnico { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<short> IdEstado { get; set; }
        public Nullable<int> IdSubTipoConvalidacion { get; set; }
        public string NumeroResolucion { get; set; }
        public string NumeroInformeTecnico { get; set; }
        public Nullable<int> IdInscripcionCarrera { get; set; }
        public Nullable<short> IdCargo { get; set; }
        public string NumeroArticulo { get; set; }
        public Nullable<int> Paso { get; set; }
    
        public virtual InscripcionCarrera InscripcionCarrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleConvalidacion> DetalleConvalidacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleHomologacion> DetalleHomologacion { get; set; }
        public virtual SubTipoConvalidacion SubTipoConvalidacion { get; set; }
    }
}
